services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5328:5328"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
