services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
