FROM node:18-alpine

WORKDIR /app

COPY package*.json .
COPY tsconfig.json next.config.js tailwind.config.js postcss.config.js components.json ./

RUN npm install

COPY app ./app
COPY public ./app

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]